// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/video_file.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7260572059221251547),
      name: 'VideoFile',
      lastPropertyId: const IdUid(4, 8825579312505047835),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3363374863360473467),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1576484810646021191),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 8687047931407882459),
            name: 'videoLocation',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8825579312505047835),
            name: 'thumbnailLocation',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 7260572059221251547),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    VideoFile: EntityDefinition<VideoFile>(
        model: _entities[0],
        toOneRelations: (VideoFile object) => [],
        toManyRelations: (VideoFile object) => {},
        getId: (VideoFile object) => object.id,
        setId: (VideoFile object, int id) {
          object.id = id;
        },
        objectToFB: (VideoFile object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final videoLocationOffset = fbb.writeString(object.videoLocation);
          final thumbnailLocationOffset =
              fbb.writeString(object.thumbnailLocation);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, videoLocationOffset);
          fbb.addOffset(3, thumbnailLocationOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = VideoFile(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              videoLocation: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              thumbnailLocation: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [VideoFile] entity fields to define ObjectBox queries.
class VideoFile_ {
  /// see [VideoFile.id]
  static final id = QueryIntegerProperty<VideoFile>(_entities[0].properties[0]);

  /// see [VideoFile.name]
  static final name =
      QueryStringProperty<VideoFile>(_entities[0].properties[1]);

  /// see [VideoFile.videoLocation]
  static final videoLocation =
      QueryStringProperty<VideoFile>(_entities[0].properties[2]);

  /// see [VideoFile.thumbnailLocation]
  static final thumbnailLocation =
      QueryStringProperty<VideoFile>(_entities[0].properties[3]);
}
